import { PrismaClient, SourceType, SectorType, SourceStatus, LicensingStatus, AccessMethod } from '@prisma/client';

const prisma = new PrismaClient();

const PRIMARY_DATA_SOURCES = [
  // Priority 1
  {
    sourceId: 'data_gov_in',
    organization: 'National Informatics Centre (NIC) / MeitY',
    sourceName: 'Data.gov.in Open Government Data (OGD) Platform',
    sourceType: SourceType.open_data_platform,
    sector: SectorType.open_data,
    geographicCoverage: 'National',
    institutionTypes: ['School', 'College', 'University'],
    officialUrl: 'https://data.gov.in',
    termsUrl: 'https://data.gov.in/terms-and-conditions',
    licensingStatus: LicensingStatus.OPEN_LICENSE,
    accessMethod: AccessMethod.API,
    apiAvailable: true,
    apiDocumentationUrl: 'https://data.gov.in/developer',
    downloadAvailable: true,
    downloadFormats: ['CSV', 'JSON', 'XML'],
    machineReadability: 'High',
    authenticationRequired: true,
    captchaRequired: false,
    updateFrequency: 'Quarterly',
    uniqueIdentifiers: ['udise_code', 'aishe_code'],
    estimatedCoverage: '1,500,000+ Schools & Colleges',
    authorityScore: 98.0,
    coverageScore: 95.0,
    freshnessScore: 85.0,
    machineReadabilityScore: 90.0,
    identifierScore: 95.0,
    automationScore: 85.0,
    overallScore: 91.3,
    ingestionPriority: 1,
    status: SourceStatus.VERIFIED,
    notes: 'Official Open Government Data License - India. Clean API structure.'
  },
  {
    sourceId: 'ndap_portal',
    organization: 'NITI Aayog',
    sourceName: 'National Data and Analytics Platform (NDAP)',
    sourceType: SourceType.open_data_platform,
    sector: SectorType.open_data,
    geographicCoverage: 'National',
    institutionTypes: ['School', 'College', 'University'],
    officialUrl: 'https://ndap.niti.gov.in',
    termsUrl: 'https://ndap.niti.gov.in/terms-of-use',
    licensingStatus: LicensingStatus.REUSE_ALLOWED,
    accessMethod: AccessMethod.DIRECT_DOWNLOAD,
    apiAvailable: true,
    downloadAvailable: true,
    downloadFormats: ['CSV', 'JSON'],
    machineReadability: 'High',
    authenticationRequired: false,
    captchaRequired: false,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['udise_code', 'aishe_code'],
    estimatedCoverage: 'National Census Datasets',
    authorityScore: 98.0,
    coverageScore: 90.0,
    freshnessScore: 80.0,
    machineReadabilityScore: 95.0,
    identifierScore: 90.0,
    automationScore: 80.0,
    overallScore: 88.8,
    ingestionPriority: 1,
    status: SourceStatus.VERIFIED,
    notes: 'NITI Aayog standardized cross-sectoral education data.'
  },
  {
    sourceId: 'aishe_portal',
    organization: 'Ministry of Education',
    sourceName: 'All India Survey on Higher Education (AISHE)',
    sourceType: SourceType.government_portal,
    sector: SectorType.higher_education,
    geographicCoverage: 'National',
    institutionTypes: ['College', 'University', 'Standalone_Institute'],
    officialUrl: 'https://aishe.gov.in',
    termsUrl: 'https://aishe.gov.in/aishe/termsCondition',
    licensingStatus: LicensingStatus.REUSE_ALLOWED,
    accessMethod: AccessMethod.DIRECT_DOWNLOAD,
    apiAvailable: false,
    downloadAvailable: true,
    downloadFormats: ['PDF', 'XLSX'],
    machineReadability: 'Medium',
    authenticationRequired: false,
    captchaRequired: false,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['aishe_code'],
    estimatedCoverage: '50,000+ Colleges & Universities',
    authorityScore: 100.0,
    coverageScore: 98.0,
    freshnessScore: 85.0,
    machineReadabilityScore: 70.0,
    identifierScore: 100.0,
    automationScore: 65.0,
    overallScore: 86.3,
    ingestionPriority: 1,
    status: SourceStatus.VERIFIED,
    notes: 'Definitive registry for AISHE Code mapping.'
  },

  // Priority 2
  {
    sourceId: 'ugc_portal',
    organization: 'University Grants Commission (UGC)',
    sourceName: 'UGC University Directory & Recognition Portal',
    sourceType: SourceType.regulatory_council,
    sector: SectorType.higher_education,
    geographicCoverage: 'National',
    institutionTypes: ['University', 'College'],
    officialUrl: 'https://www.ugc.gov.in',
    licensingStatus: LicensingStatus.REUSE_RESTRICTED,
    accessMethod: AccessMethod.MANUAL_REVIEW,
    apiAvailable: false,
    downloadAvailable: true,
    downloadFormats: ['PDF'],
    machineReadability: 'Medium',
    authenticationRequired: false,
    captchaRequired: false,
    updateFrequency: 'Monthly',
    uniqueIdentifiers: ['ugc_id'],
    estimatedCoverage: '1,100+ Universities',
    authorityScore: 100.0,
    coverageScore: 100.0,
    freshnessScore: 90.0,
    machineReadabilityScore: 60.0,
    identifierScore: 95.0,
    automationScore: 50.0,
    overallScore: 82.5,
    ingestionPriority: 2,
    status: SourceStatus.UNDER_REVIEW,
    notes: 'Official University recognition status.'
  },
  {
    sourceId: 'udise_plus',
    organization: 'Ministry of Education / Department of School Education',
    sourceName: 'Unified District Information System for Education Plus (UDISE+)',
    sourceType: SourceType.government_portal,
    sector: SectorType.school_education,
    geographicCoverage: 'National',
    institutionTypes: ['School'],
    officialUrl: 'https://udiseplus.gov.in',
    termsUrl: 'https://udiseplus.gov.in/terms',
    licensingStatus: LicensingStatus.REUSE_STATUS_UNCLEAR,
    accessMethod: AccessMethod.MANUAL_REVIEW,
    apiAvailable: false,
    downloadAvailable: true,
    downloadFormats: ['XLSX', 'PDF'],
    machineReadability: 'Medium',
    authenticationRequired: true,
    captchaRequired: true,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['udise_code'],
    estimatedCoverage: '1,480,000+ Schools',
    authorityScore: 100.0,
    coverageScore: 100.0,
    freshnessScore: 85.0,
    machineReadabilityScore: 70.0,
    identifierScore: 100.0,
    automationScore: 30.0,
    overallScore: 80.8,
    ingestionPriority: 2,
    status: SourceStatus.UNDER_REVIEW,
    notes: 'CAPTCHA protected portal. Downloadable reports require manual extraction.'
  },

  // Priority 3
  {
    sourceId: 'cbse_saras',
    organization: 'Central Board of Secondary Education (CBSE)',
    sourceName: 'CBSE SARAS Affiliation Portal',
    sourceType: SourceType.regulatory_council,
    sector: SectorType.school_education,
    geographicCoverage: 'National',
    institutionTypes: ['School'],
    officialUrl: 'https://saras.cbse.gov.in',
    licensingStatus: LicensingStatus.REUSE_STATUS_UNCLEAR,
    accessMethod: AccessMethod.MANUAL_REVIEW,
    apiAvailable: false,
    downloadAvailable: false,
    machineReadability: 'Low',
    authenticationRequired: false,
    captchaRequired: true,
    updateFrequency: 'Monthly',
    uniqueIdentifiers: ['cbse_id'],
    estimatedCoverage: '28,000+ Affiliated Schools',
    authorityScore: 95.0,
    coverageScore: 95.0,
    freshnessScore: 90.0,
    machineReadabilityScore: 50.0,
    identifierScore: 95.0,
    automationScore: 20.0,
    overallScore: 74.2,
    ingestionPriority: 3,
    status: SourceStatus.DISCOVERED,
    notes: 'CAPTCHA active. Mark for human review.'
  },
  {
    sourceId: 'aicte_portal',
    organization: 'All India Council for Technical Education (AICTE)',
    sourceName: 'AICTE Approved Institutes Portal',
    sourceType: SourceType.regulatory_council,
    sector: SectorType.higher_education,
    geographicCoverage: 'National',
    institutionTypes: ['College', 'Standalone_Institute'],
    officialUrl: 'https://www.aicte-india.org',
    licensingStatus: LicensingStatus.REUSE_STATUS_UNCLEAR,
    accessMethod: AccessMethod.DIRECT_DOWNLOAD,
    apiAvailable: false,
    downloadAvailable: true,
    downloadFormats: ['XLSX'],
    machineReadability: 'High',
    authenticationRequired: false,
    captchaRequired: false,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['aicte_id'],
    estimatedCoverage: '10,000+ Technical Colleges',
    authorityScore: 95.0,
    coverageScore: 90.0,
    freshnessScore: 85.0,
    machineReadabilityScore: 85.0,
    identifierScore: 90.0,
    automationScore: 75.0,
    overallScore: 86.6,
    ingestionPriority: 3,
    status: SourceStatus.DISCOVERED,
    notes: 'Annual approved technical college list.'
  },
  {
    sourceId: 'nirf_ranking',
    organization: 'National Institutional Ranking Framework (NIRF)',
    sourceName: 'NIRF Annual India Rankings',
    sourceType: SourceType.government_portal,
    sector: SectorType.higher_education,
    geographicCoverage: 'National',
    institutionTypes: ['College', 'University'],
    officialUrl: 'https://www.nirfindia.org',
    licensingStatus: LicensingStatus.REUSE_ALLOWED,
    accessMethod: AccessMethod.DIRECT_DOWNLOAD,
    apiAvailable: false,
    downloadAvailable: true,
    downloadFormats: ['PDF', 'HTML'],
    machineReadability: 'Medium',
    authenticationRequired: false,
    captchaRequired: false,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['nirf_id', 'aishe_code'],
    estimatedCoverage: ' Top 100 - 200 Institutes per Discipline',
    authorityScore: 100.0,
    coverageScore: 40.0,
    freshnessScore: 95.0,
    machineReadabilityScore: 65.0,
    identifierScore: 85.0,
    automationScore: 60.0,
    overallScore: 74.2,
    ingestionPriority: 3,
    status: SourceStatus.DISCOVERED,
    notes: 'Official ranking disclosures.'
  },

  // Priority 4 (Professional Regulators & Bodies)
  {
    sourceId: 'cisce_locator',
    organization: 'Council for the Indian School Certificate Examinations (CISCE)',
    sourceName: 'CISCE School Locator',
    sourceType: SourceType.regulatory_council,
    sector: SectorType.school_education,
    geographicCoverage: 'National',
    institutionTypes: ['School'],
    officialUrl: 'https://cisce.org',
    licensingStatus: LicensingStatus.UNKNOWN,
    accessMethod: AccessMethod.MANUAL_REVIEW,
    apiAvailable: false,
    downloadAvailable: false,
    machineReadability: 'Low',
    authenticationRequired: false,
    captchaRequired: true,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['cisce_code'],
    estimatedCoverage: '2,800+ ICSE/ISC Schools',
    authorityScore: 95.0,
    coverageScore: 80.0,
    freshnessScore: 85.0,
    machineReadabilityScore: 40.0,
    identifierScore: 90.0,
    automationScore: 20.0,
    overallScore: 68.3,
    ingestionPriority: 4,
    status: SourceStatus.DISCOVERED,
    notes: 'CISCE school directory.'
  },
  {
    sourceId: 'kvs_sangathan',
    organization: 'Kendriya Vidyalaya Sangathan (KVS)',
    sourceName: 'KVS School Directory',
    sourceType: SourceType.government_portal,
    sector: SectorType.school_education,
    geographicCoverage: 'National',
    institutionTypes: ['School'],
    officialUrl: 'https://kvsangathan.nic.in',
    licensingStatus: LicensingStatus.REUSE_ALLOWED,
    accessMethod: AccessMethod.DIRECT_DOWNLOAD,
    apiAvailable: false,
    downloadAvailable: true,
    downloadFormats: ['PDF'],
    machineReadability: 'Medium',
    authenticationRequired: false,
    captchaRequired: false,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['udise_code', 'cbse_id'],
    estimatedCoverage: '1,250+ Kendriya Vidyalayas',
    authorityScore: 95.0,
    coverageScore: 100.0,
    freshnessScore: 85.0,
    machineReadabilityScore: 60.0,
    identifierScore: 90.0,
    automationScore: 60.0,
    overallScore: 81.6,
    ingestionPriority: 4,
    status: SourceStatus.DISCOVERED,
    notes: 'Central government school chain.'
  },
  {
    sourceId: 'nmc_medical',
    organization: 'National Medical Commission (NMC)',
    sourceName: 'NMC Approved Medical Colleges Registry',
    sourceType: SourceType.regulatory_council,
    sector: SectorType.higher_education,
    geographicCoverage: 'National',
    institutionTypes: ['College', 'University'],
    officialUrl: 'https://www.nmc.org.in',
    licensingStatus: LicensingStatus.REUSE_STATUS_UNCLEAR,
    accessMethod: AccessMethod.MANUAL_REVIEW,
    apiAvailable: false,
    downloadAvailable: false,
    machineReadability: 'Low',
    authenticationRequired: false,
    captchaRequired: true,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['nmc_id'],
    estimatedCoverage: '700+ Medical Colleges',
    authorityScore: 100.0,
    coverageScore: 100.0,
    freshnessScore: 90.0,
    machineReadabilityScore: 40.0,
    identifierScore: 90.0,
    automationScore: 20.0,
    overallScore: 73.3,
    ingestionPriority: 4,
    status: SourceStatus.DISCOVERED,
    notes: 'NMC MBBS college recognition.'
  },
  {
    sourceId: 'bci_law',
    organization: 'Bar Council of India (BCI)',
    sourceName: 'BCI Approved Law Colleges Directory',
    sourceType: SourceType.regulatory_council,
    sector: SectorType.higher_education,
    geographicCoverage: 'National',
    institutionTypes: ['College', 'University'],
    officialUrl: 'http://www.barcouncilofindia.org',
    licensingStatus: LicensingStatus.UNKNOWN,
    accessMethod: AccessMethod.MANUAL_REVIEW,
    apiAvailable: false,
    downloadAvailable: true,
    downloadFormats: ['PDF'],
    machineReadability: 'Low',
    authenticationRequired: false,
    captchaRequired: false,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['bci_id'],
    estimatedCoverage: '1,500+ Law Faculties',
    authorityScore: 95.0,
    coverageScore: 90.0,
    freshnessScore: 80.0,
    machineReadabilityScore: 40.0,
    identifierScore: 85.0,
    automationScore: 30.0,
    overallScore: 70.0,
    ingestionPriority: 4,
    status: SourceStatus.DISCOVERED,
    notes: 'BCI law center list.'
  },

  // Priority 5 (State-specific Sources)
  {
    sourceId: 'up_higher_education',
    organization: 'Department of Higher Education, Uttar Pradesh',
    sourceName: 'UP State Higher Education Portal',
    sourceType: SourceType.state_admission_cell,
    sector: SectorType.state_admission,
    geographicCoverage: 'State: UP',
    institutionTypes: ['College', 'University'],
    officialUrl: 'https://uphed.gov.in',
    licensingStatus: LicensingStatus.REUSE_STATUS_UNCLEAR,
    accessMethod: AccessMethod.MANUAL_REVIEW,
    apiAvailable: false,
    downloadAvailable: true,
    downloadFormats: ['PDF'],
    machineReadability: 'Medium',
    authenticationRequired: false,
    captchaRequired: false,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['aishe_code'],
    estimatedCoverage: 'UP Colleges & State Universities',
    authorityScore: 90.0,
    coverageScore: 85.0,
    freshnessScore: 80.0,
    machineReadabilityScore: 50.0,
    identifierScore: 80.0,
    automationScore: 40.0,
    overallScore: 70.8,
    ingestionPriority: 5,
    status: SourceStatus.DISCOVERED,
    notes: 'Uttar Pradesh higher education directory.'
  },
  {
    sourceId: 'maharashtra_cet_cell',
    organization: 'State Common Entrance Test Cell, Maharashtra',
    sourceName: 'MH CET Admission Portal',
    sourceType: SourceType.state_admission_cell,
    sector: SectorType.state_admission,
    geographicCoverage: 'State: MH',
    institutionTypes: ['College'],
    officialUrl: 'https://cetcell.mahacet.org',
    licensingStatus: LicensingStatus.REUSE_STATUS_UNCLEAR,
    accessMethod: AccessMethod.MANUAL_REVIEW,
    apiAvailable: false,
    downloadAvailable: true,
    downloadFormats: ['PDF', 'HTML'],
    machineReadability: 'Medium',
    authenticationRequired: false,
    captchaRequired: true,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['aicte_id'],
    estimatedCoverage: 'Maharashtra Professional Colleges',
    authorityScore: 90.0,
    coverageScore: 85.0,
    freshnessScore: 90.0,
    machineReadabilityScore: 50.0,
    identifierScore: 80.0,
    automationScore: 30.0,
    overallScore: 70.8,
    ingestionPriority: 5,
    status: SourceStatus.DISCOVERED,
    notes: 'Maharashtra MHT-CET seat matrix.'
  },
  {
    sourceId: 'tn_tnea_portal',
    organization: 'Directorate of Technical Education, Tamil Nadu',
    sourceName: 'Tamil Nadu Engineering Admissions (TNEA) Portal',
    sourceType: SourceType.state_admission_cell,
    sector: SectorType.state_admission,
    geographicCoverage: 'State: TN',
    institutionTypes: ['College'],
    officialUrl: 'https://www.tneaonline.org',
    licensingStatus: LicensingStatus.REUSE_STATUS_UNCLEAR,
    accessMethod: AccessMethod.MANUAL_REVIEW,
    apiAvailable: false,
    downloadAvailable: true,
    downloadFormats: ['PDF'],
    machineReadability: 'Medium',
    authenticationRequired: false,
    captchaRequired: false,
    updateFrequency: 'Annual',
    uniqueIdentifiers: ['aicte_id'],
    estimatedCoverage: '500+ Engineering Colleges in TN',
    authorityScore: 90.0,
    coverageScore: 85.0,
    freshnessScore: 90.0,
    machineReadabilityScore: 60.0,
    identifierScore: 80.0,
    automationScore: 50.0,
    overallScore: 75.8,
    ingestionPriority: 5,
    status: SourceStatus.DISCOVERED,
    notes: 'TNEA counselling cutoff list.'
  }
];

async function main() {
  console.log('🧹 Clearing existing Data Source Registry...');
  await prisma.sourceRecord.deleteMany();
  await prisma.externalIdentifier.deleteMany();
  await prisma.ingestionRun.deleteMany();
  await prisma.dataImport.deleteMany();
  await prisma.dataSource.deleteMany();

  console.log('📦 Provisioning Data Source Registry entries...');
  for (const src of PRIMARY_DATA_SOURCES) {
    await prisma.dataSource.create({
      data: src as any
    });
  }

  console.log(`✅ Provisioned ${PRIMARY_DATA_SOURCES.length} authoritative Indian Education Data Sources in Registry!`);
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
